import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ContextProvider from "./providers/ContextProvider";
import Navigation from "./components/Navigation/Navigation";
import Footer from "./components/Footer/Footer";
import MiniFriendChat from "./components/PathBased/MiniFriendChat";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <head>
                <link
                    rel="stylesheet"
                    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
                    integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
                    crossOrigin="anonymous"
                    referrerPolicy="no-referrer"
                />
                {/* <!-- from cdn --> */}
                <script
                    async
                    src="https://unpkg.com/@material-tailwind/html@latest/scripts/ripple.js"
                ></script>
            </head>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ContextProvider>
                    <div className="root">
                        <Navigation />
                        <MiniFriendChat />
                        {children}
                        <Footer />
                    </div>
                </ContextProvider>
            </body>
        </html>
    );
}
